#### general settings
name: LOLv2_synthetic_model
use_tb_logger: true
model: video_base4
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: indoor
    mode: lolv2_syn
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: ../Data/LOL-v2/Synthetic/Train/Normal
    dataroot_LQ: ../Data/LOL-v2/Synthetic/Train/Low
    train_size: [384, 384]
    cache_keys: ~
    cache_data: true
    padding: new_info

    N_frames: 5     # how many frames as a input.
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 32
    GT_size: 128     # size you want to crop out as input sample.
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS4
    mode: lolv2_syn
    dataroot_GT: ../Data/LOL-v2/Synthetic/Test/Normal
    dataroot_LQ: ../Data/LOL-v2/Synthetic/Test/Low
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [384, 384]


#### path
path:
  root: ./
  strict_load: false

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 80000
  ft_tsa_only: 0
  warmup_iter: -1  # -1: no warm up
  lr_steps: [10000, 20000, 40000, 60000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
